apiVersion: v1
kind: Service
metadata:
  name: todo-lb-service
  labels:
    app: todo-lb-service
spec:
  type: LoadBalancer
  selector:
    app: todo-app  
  ports:
  - port: 3000
  externalIPs:
  - 192.168.49.2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service
  labels:
    app: todo-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app-service
        image: dockrtraining/todo-app
        ports:
        - containerPort: 3000     